import type { Metadata } from "next";

import "./globals.css";
import { SocketProvider } from "@/components/SocketProvider";
import { Toaster } from 'react-hot-toast';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body

      >
      <SocketProvider>
          {children}
          <Toaster
              position="top-right"
              toastOptions={{
                  style: {
                      background: '#fff',
                      color: '#333',
                      borderRadius: '12px',
                      padding: '10px 14px',
                      boxShadow: '0 3px 10px rgba(0,0,0,0.1)',
                  },
              }}
          />
      </SocketProvider>
      </body>
    </html>
  );
}
